### ISSUE TITLE
fastify-plugin option

### ISSUE THREAD

**Issue by rubybb** [fastify/fastify-autoload#101]
## 🚀 Feature Proposal

An option in the plugin for wrapping the export in a ``fastify-plugin``.

## Motivation

It'd make all my plugins cleaner by just having an option to specific if it needs to be wrapped or not.
requiring ``fastify-plugin`` in each plugin file is annoying and tedious, this would clean lots of code up a bit and wouldn't affect existing code.

## Example

```js

module.exports = async function (app, options) {
    ...
}

module.exports.wrap = true
```

**Comment by jsumners** [comment]
`fastify-plugin` is not a requirement for plugins. It is merely a helper for overriding scope and providing utility around verifying requirements are present. Both things are quite situational to the plugin being written. It seems to me blindly applying these things to all plugins is not such a great practice.

**Comment by rubybb** [comment]
> `fastify-plugin` is not a requirement for plugins. It is merely a helper for overriding scope and providing utility around verifying requirements are present. Both things are quite situational to the plugin being written. It seems to me blindly applying these things to all plugins is not such a great practice.

I agree, and I know what it's used for, I'm simply saying it'd be nice feature to have for making it easier to prevent encapsulation of the plugin if you don't want it to be.

**Comment by mcollina** [comment]
I'm not in favor of this change because it would make each plugin not being loadable by fastify itself without change.

Note that using the proposed `wrap` property has the same line impact of using `fastify-plugin`: 1. If you do not want add the dependency you can just add the symbol and all the needed properties.
