### ISSUE TITLE
Create tests for ts-node and ts-node-dev

### ISSUE THREAD

**Issue by RafaelGSS** [fastify/fastify-autoload#102]
Reference: #100 

We discover that our tests not cover some tools, so, is important to create tests that cover `ts-node` and `ts-node-dev` tool.

**Comment by climba03003** [comment]
I do not think ```ts-node-dev``` should be tested. If ```ts-node``` test is pass, ```ts-node-dev``` should eventually pass too.
More simple is that, if ```typescript``` test is pass, both ```ts-node``` and ```ts-node-dev``` should pass too.

**Comment by RafaelGSS** [comment]
Not stale

**Comment by RafaelGSS** [comment]
@mcollina `request` has a typo on the label. I don't have permission for change on this repo, can you fix?

**Comment by mcollina** [comment]
> @mcollina `request` has a typo on the label. I don't have permission for change on this repo, can you fix?

done
