### ISSUE TITLE
Extra "/" is appended to route url when load file from subfolder with depth >= 2

### ISSUE THREAD

**Issue by abhaydgarg** [fastify/fastify-autoload#122]
## Directory Structure

- projects
  - abc
    - xyz
      - index.js 

## index.js File

This file contains the routes.

```js
module.exports = function (app, options, done) {
  app.get('/users', (request, reply) => {
    reply.send({ data: 'users' })
  })

  done()
}
```

## Autoload Config

```js
app.register(autoload, {
  dir: path.join(__dirname, 'projects'),
  dirNameRoutePrefix: false,
  options: {
    prefix: '/projects/:id'
  }
})
```

## Route's URL Generated 

`/projects/:id//users`

There are two `//` before `users`. 

This is happening because the `index.js` file is in subfolder `xyz`. I have tested it by creating one more subfolder inside `xyz`  and put `index.js` file inside it. The url i get then `/projects/:id///users`.  This time three `/`.

If I set `dirNameRoutePrefix: true` then I do not get extra `/` but then it add the folder name in url that i do not want.

## Expected Route's URL

`/projects/:id/users`

**Comment by mcollina** [comment]
Would you like to send a Pull Request to address this issue? Remember to add unit tests.
