### ISSUE TITLE
Support route parameters in folder names 

### ISSUE THREAD

**Issue by mcollina** [fastify/fastify-autoload#133]
## 🚀 Feature Proposal

We should support automatic routes for route params, as example `/user/:userId/cart`

```
├── routes
│   ├── user
│   │   ├── _userId
│   │       └── cart.js
├── package.json
└── app.js
```

I would recommend we convert `_` to `:` on loading.

**Comment by zekth** [comment]
I like this implementation and a good feature would be the generation of the scaffolding using `fastify-cli`.

**Comment by jsumners** [comment]
With as many customizations this module is getting for hooking into the algorithm, it might just be better to require an `autoload.{json,yaml}` file that has mappings and other configurations.

**Comment by mcollina** [comment]
I tend to agree?

**Comment by polymathca** [comment]
> 
> 
> With as many customizations this module is getting for hooking into the algorithm, it might just be better to require an `autoload.{json,yaml}` file that has mappings and other configurations.

Were you thinking it would live in the root of the folder from which plugins are being loaded, or in a separate config folder elsewhere in the project?

**Comment by jsumners** [comment]
> > With as many customizations this module is getting for hooking into the algorithm, it might just be better to require an `autoload.{json,yaml}` file that has mappings and other configurations.
> 
> Were you thinking it would live in the root of the folder from which plugins are being loaded, or in a separate config folder elsewhere in the project?

I imagine it would be a file within each directory that is loaded:

```
/project
  \__ /plugins
          \__ /plugin1
                 \__ autoload.yaml
```

🤷‍♂️  I'm just making an observation. It could be an unworkable idea or not worth the effort. I really do not know.

**Comment by delvedor** [comment]
I like using the folder names for generating the path, it's a well-established pattern in the node community.
Something like:
```

├── routes
│   ├── user
│   │   ├── [userId]
│   │       └── cart.js
├── package.json
└── app.js
```

Configuration files could work as well, but yaml are very easy to misconfigure. Furthermore, at that point, you could just use the `autoPrefix` export 🤔 .

**Comment by fox1t** [comment]
I like the idea of using the filesystem since it is a pattern popularized by Next.js. I don't like having a separate folder for routes: usually, I divide the code by "services ."I think that using a `yml` provides more flexibility, though. 

We might support both, starting from the filesystem thing?

**Comment by mcollina** [comment]
FYI, I think the yml/json file is orthogonal to this issue, maybe we can split it?

**Comment by polymathca** [comment]
> 
> 
> I like using the folder names for generating the path, it's a well-established pattern in the node community.

I agree, I think the FS-based route hierarchy is easy to grasp, predictably follows the conventions you'd expect to see in a web application, and is handled very well by this plugin. I like @mcollina's suggestion of adding the option to include parameters, as I think that complements the functionality here quite well and doesn't add too many more new moving parts.

> Configuration files could work as well, but yaml are very easy to misconfigure. Furthermore, at that point, you could just use the `autoPrefix` export 🤔 .

> 
> 
> FYI, I think the yml/json file is orthogonal to this issue, maybe we can split it?

I think that it would likely be more appropriate as its own plugin if it's not using the FS for routing, but I'm not sure what that would look like.

**Comment by arthur-fontaine** [comment]
Is there a release date for this PR?

**Comment by mcollina** [comment]
Thanks for the ping, I missed the last round of edit in the PR. It just miss docs.
