### ISSUE TITLE
ts-jest detection broken with npm 7

### ISSUE THREAD

**Issue by jclem** [fastify/fastify-autoload#145]
## 🐛 Bug Report

In npm 7, environment variables like `npm_package_devDependencies*` environment variables are no longer present, and so [this check](https://github.com/fastify/fastify-autoload/blob/f8a2a9930f0635c0c25cf07d53a875de5c0bfc82/index.js#L11) that fastify-autoload performs to determine whether ts-jest is present is no longer working.

 Would it be possible to expose `typescriptSupport` as a configuration option, so that there's an escape hatch in circumstances where detection does not work?

## To Reproduce

1. Install npm 7
2. Run `npm run typescript:jest` in this package

## Expected behavior

The tests should pass, but instead, the same error described in [this issue](https://github.com/fastify/fastify-autoload/issues/86) occurs.
## Your Environment

- *node version*: 115
- *fastify version*: 3.5.2
- *os*: macOS

**Comment by mcollina** [comment]
Should be fixed in v3.6.0
