### ISSUE TITLE
Object Syntax

### ISSUE THREAD

**Issue by galvez** [fastify/fastify-autoload#148]
## 🚀 Feature Proposal

A way to define plugins as objects.

## Motivation

Less code to write for simple plugins, smaller, compact format when it makes sense.

## Examples

```js
export default {
  decorate: {
    helper () {
      console.log('helper')
    }
  },
  decorateRequest: {
    $placeholder: null
  },
  async onRequest (req) {
    req.$placeholder = 'something'
  },
}
```

With `fastify-plugin`:

```js
export default {
  encapsulate: true,
  decorate: {
    helper () {
      console.log('helper')
    }
  },
  decorateRequest: {
    $placeholder: null
  },
  async onRequest (req) {
    req.$placeholder = 'something'
  },
}
```

**Comment by mcollina** [comment]
How are routes defined?

**Comment by galvez** [comment]
I'm thinking for me this would be the most ergonomic:

```js
export default {
  routes ({ get, post, put, del }) {
    get('/myroute', () => {}))
  }
}
```

The method setter helpers would be bind to `fastify` automatically so we can destructure them like that.

**Comment by RafaelGSS** [comment]
I like this idea, however, I feel that whoever uses `fastify-autload` will be a bit stuck in this plugin development. I mean, the fastify approach would be created under the hood, and in case of a new feature in Fastify, they will need to wait for a release of `fastify-autoload` as well.

It might be a good idea to a new plugin that can be used along with `fastify-autload`.

**Comment by galvez** [comment]
Here you go -- https://github.com/galvez/fastify-apply -- `npm i fastify-apply`. 

Please review @mcollina @delvedor @RafaelGSS 🙏

**Comment by fox1t** [comment]
I am not sure I like the idea of having another method to register a plugin. The exposed surface is already broad, and it isn't easy for a newcomer to even understand what is going on during the boot or the req/res cycle.

I think that this functionality is a perfect match for a fastify-plugin itself, though. :)
