### ISSUE TITLE
Feature Request: Some method to resolve all routes/plugins/options for bundling

### ISSUE THREAD

**Issue by josh-hemphill** [fastify/fastify-autoload#160]
## 🚀 Feature Proposal

Especially when using typescript, some end up running fastify through a bundler and treeshaking etc. It would be nice if some method was exposed to resolve everything immediately so that it can also be run through the bundler too.

## Motivation

Currently, using a bundler with fastify-autoload results in either not bundling the autoloaded routes or having to do a bunch of otherwise unnecessary internal virtual module resolution. 

## Example

```ts
import autoLoad from 'fastify-autoload'
export default const resolved = autoLoad.resolve(options)
```

**Comment by mcollina** [comment]
Sounds good to me.

Would you like to send a Pull Request to address this issue? Remember to add unit tests.

**Comment by mcollina** [comment]
Are you sure this would work? autoLoad would use dynamic import anyway to load all the files - I don't think bundlers can do this.

**Comment by josh-hemphill** [comment]
They can know to include the files as virtual imports, so they still get bundled, but then there's still a lot of unnecessary resolution logic that happens since it wouldn't know how they're being imported, and doing it this way might also prevent treeshaking.
I guess ideally, there would be a way to serialize the final state of fastify-autoload after all the resolution happens.
So perhaps it would be better suited to bundler-specific plugins. 🤷 I'm not sure.

**Comment by mcollina** [comment]
Give it a spin and see if you can find a way to make this work! I don't bundle my server side code.

**Comment by alexcroox** [comment]
Did this go anywhere? Looking to deploy this to AWS Lambda which has package size limits meaning you have to bundle your code for any reasonably sized API.

**Comment by josh-hemphill** [comment]
Nope, I started looking at the internals of fastify-autoload, and it wasn't very conducive to doing something like that. It would have to be it's own solution for loading fastify routes and I don't have the bandwidth to take on something like that.
