### ISSUE TITLE
why files other index.js don't work?

### ISSUE THREAD

**Issue by qhoirulanwar** [fastify/fastify-autoload#17]
why files other index.js don't work?

I have a list-item.js file and there is a route in the file that has autoload register,
but the route cannot be accessed by the browser and autoload

**Comment by mcollina** [comment]
what do you mean? autoload loads all files and folders on a single level. It relies on Node.js logic of loading a directory. You can add a `package.json` file in those folder if you want to load a different file rather than `index.js`.

**Comment by qhoirulanwar** [comment]
`fastify.register(AutoLoad, {
    dir: path.join(__dirname, 'src/api'),
    options: {}
})`

![capture](https://user-images.githubusercontent.com/22901097/47965101-392f5980-e075-11e8-957b-e7bc99b60827.PNG)

**Comment by qhoirulanwar** [comment]
`fastify.register(AutoLoad, {
    dir: path.join(__dirname, 'src/api'),
    options: {}
})`

![capture](https://user-images.githubusercontent.com/22901097/47965101-392f5980-e075-11e8-957b-e7bc99b60827.PNG)

![capture1](https://user-images.githubusercontent.com/22901097/47965154-28cbae80-e076-11e8-9790-c9dc720cd9ae.PNG)

**Comment by mcollina** [comment]
Autoloads just load one level. Additional files in there are meant for support. You can use multiple autoloads to load recursively.

**Comment by RafaelGSS** [comment]
Hello @mcollina, this can be a good feature, right?

Maybe I can work on it.

**Comment by mcollina** [comment]
This could be a cool feature if we automatically set the folder name as the prefix, and we registered plugins recursively.
I would put all of that behind a flag.
