### ISSUE TITLE
Add register priority based on plugin type

### ISSUE THREAD

**Issue by MSE99** [fastify/fastify-autoload#183]
## 🚀 Feature Proposal

Add the ability to customize the order in which fastify-autoload registers plugins, plugins
can  export an additional property called `priority`.

```js
module.exports = async function () {}
module.exports.priority = 'plugin'
```

autoload will then sort all the plugins based on their priority and register them, the plugins should be sorted like:

1. `plugin`
2. `decorator`
3. `hook`
4. `service`

similar to how fastify docs [recommends](https://www.fastify.io/docs/latest/Getting-Started/#loading-order-of-your-plugins) how to order the register calls to load your plugins.

## Motivation

This would make fastify-autoload more developer friendly.

## Example

For example we have the following few plugins:

`shared/constants.js`
```js
const fp = require('fastify-plugin')

async function constants () {
   // .....
}

module.exports = fp(constants)
module.exports.priority = 'decorator'
```

`shared/authHooks.js`
```js
const fp = require('fastify-plugin')

async function authHooks () {
  // ....
}

module.exports = fp(authHook)
module.exports.priority = 'hook'
```

`app.js`
```js
const path = require('path')
const Fastify = require('fastify')
const autoload = require('autoload')

const app = Fastify({ logger: false })

app.register(autoload, { dir: path.join(__dirname, 'shared') })
app.listen(8080)
```

Here autoload will always register the decorator plugin before the hooks plugin.

**Comment by climba03003** [comment]
Most of the time you will use the `plugin` by feature. AFAIK, `fastify-autoload` will auto resolve the dependencies between each plugin if you specify it correctly.

e.g.

```js
export default fastifyPlugin(function() {}, { name: 'foo', dependencies: ['bar'] })
export default fastifyPlugin(function() {}, { name: 'bar' })
```
Plugin `foo` should always register after plugin `bar`.
