### ISSUE TITLE
Plugin can not be used in SWC but has to be executed in ts-node

### ISSUE THREAD

**Issue by leoyli-headsup** [fastify/fastify-autoload#190]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

3.20.2

### Plugin version

3.8.1

### Node.js version

16.6.1

### Operating system

macOS

### Operating system version (i.e. 20.04, 11.3, 10)

11.5.2

### Description

Hey, I want to use this plugin in TypeScript without `ts-node`. Instead, I'm piping the project via `@swc/register` to NodeJS. But when the project starts, it shows:

>  Error: fastify-autoload cannot import plugin at 'xxx/xx.ts'. To fix this error compile TypeScript to JavaScript or use 'ts-node' to run your app.

I can apply a hacky workaround with this

```ts
      Object.assign(process, { [Symbol.for('ts-node.register.instance')]: undefined });
```

Do we really need this plugin to check if it runs in TypeScript anyway? Seems a bit redundant...

### Steps to Reproduce

- Use `@swc/register` to transpile the project by running
   ```
   node -r tsconfig-paths/register -r @swc/register server/index.ts
   ```

**Comment by mcollina** [comment]
`@swc/register` is not currently supported.
Would you like to send a Pull Request to address this issue? Remember to add unit tests.

**Comment by leoyli-headsup** [comment]
Now working like a charm, tested in our App, thanks @mcollina !
