### ISSUE TITLE
How to load a npm plugin? 

### ISSUE THREAD

**Issue by zero245** [fastify/fastify-autoload#193]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the issue has not already been raised

### Issue

What is the recommended way to load plugins that is not custom, rather installed via npm such as : https://github.com/lyquocnam/fastify-sequelize

Or this plugin only support custom plugins that are sitting in a specific folder?

**Comment by Eomm** [comment]
You need to write a file:

```
  // plugins/plugin-a.js
  const fp = require('fastify-plugin')

  function plugin (fastify, opts, next) {
    fastify.register(fsequelize, sequelizeConfig)
    next()
  }

  module.exports = fp(plugin)
```
