### ISSUE TITLE
Allow patterns with params in the middle of directory names

### ISSUE THREAD

**Issue by NakajimaTakuya** [fastify/fastify-autoload#197]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the feature has not already been requested

### 🚀 Feature Proposal

Allow patterns with params in the middle of directory names
such as case:

```javascript
/country-:county/
```

### Motivation

There are many cases where you want to handle a variable in a part of a path.
I think we should support that in this handy autoloader too.

### Example

directory:
```
/foo/country-__country/
```

cover to:
```
/foo/country-:country/
```

**Comment by mcollina** [comment]
I agree! Would you like to send a Pull Request to address this issue? Remember to add unit tests.

**Comment by NakajimaTakuya** [comment]
@mcollina 
Thanks for the response, I'll give it a go!
