### ISSUE TITLE
dirNameRoutePrefix causes prefix to appear twice

### ISSUE THREAD

**Issue by ferrao** [fastify/fastify-autoload#201]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

3.22.1

### Plugin version

3.9.0

### Node.js version

14.10.1

### Operating system

Linux

### Operating system version (i.e. 20.04, 11.3, 10)

Linux  5.14.16-arch1-1

### Description

Using the option `dirNameRoutePrefix` with a rewrite function causes the returned prefix to be used twice.

### Steps to Reproduce

Using the following option `dirNameRoutePrefix: (parent, name) => 'my-prefix'`

### Expected Behavior

All routes should have the prefix `my-prefix` but they end up as `my-prefix/my-prefix` instead.

**Comment by mcollina** [comment]
Good spot!
Would you like to send a Pull Request to address this issue? Remember to add unit tests.

**Comment by darkgl0w** [comment]
Hello.
This bug seems to have been solved. At least I can not reproduce it with `fastify-autoload@3.10.0` and `fastify@3.25.3`.

@ferrao > can you check if it's solved on your side and in the case it is not, can you provide a repo we can clone to investigate this bug please ?
