### ISSUE TITLE
SyntaxError: Unexpected token import

### ISSUE THREAD

**Issue by the-yadu** [fastify/fastify-autoload#207]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

^3.2.0

### Plugin version

^3.0.0

### Node.js version

14.17.5

### Operating system

Linux

### Operating system version (i.e. 20.04, 11.3, 10)

18

### Description

content = await import(url.pathToFileURL(file).href)
                 ^^^^^^
 SyntaxError: Unexpected token import
     at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
     at Module._compile (module.js:616:28)

### Steps to Reproduce

I am using PM2  to deploy application on digital ocean server.
Create regular fastify project and install the fastify-autoload plugin. 
It throws error on server.

It works locally.

### Expected Behavior

Should not throw the above error and should auto load all the routes

**Comment by mcollina** [comment]
I think you have some problems on your server. Don't use pm2.
