### ISSUE TITLE
Silent cascading failure when plugin parsing fails

### ISSUE THREAD

**Issue by franky47** [fastify/fastify-autoload#213]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

3.25.0

### Plugin version

3.9.0

### Node.js version

16.8.0

### Operating system

macOS

### Operating system version (i.e. 20.04, 11.3, 10)

10.14.6

### Description

When a plugin file contains the following:
- A reference error at the top-level
- A reference error in the plugin function
- A TypeScript type validation error (when invoked through `ts-node`)
- An error thrown in the plugin function

`fastify-autoload` will **silently** fail to load the plugin, and **all subsequent plugins**.

### Steps to Reproduce

Reproduction repository:
https://github.com/franky47/fastify-autoload-silent-errors

### Expected Behavior

I'd expect `fastify-autoload` to report errors:
- Parse errors when `require`'ing the plugin file
- Type errors when using TypeScript & `ts-node`
- Runtime errors thrown in the plugin function

This would let the user know something is wrong without having to check that all routes and plugins have been loaded correctly.

Ideally, having an isolation system that ensures that a plugin failure does not cascade into not loading subsequent plugins would also be helpful.

**Comment by mcollina** [comment]
Could you upload a full example to reproduce either in a zip file or a github repo?

**Comment by franky47** [comment]
I have added a GitHub repo that reproduces the error in the description, here it is again:
https://github.com/franky47/fastify-autoload-silent-errors

**Comment by mcollina** [comment]
You have a bug in your code, this would show the error:

```js

server.ready((err) => {
  if (err) throw err
  console.log(server.printRoutes())
})

```

**Comment by franky47** [comment]
Ah, thank you! I need to read the Fastify documentation more closely. 😅
