### ISSUE TITLE
Could the file support jsc?

### ISSUE THREAD

**Issue by tikkhun** [fastify/fastify-autoload#218]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the feature has not already been requested

### 🚀 Feature Proposal

Sometimes I need to convert js to bytecode(*.jsc) through "bytenode". Can autoload support loading these *.jsc files?

**Comment by mcollina** [comment]
Unfortunately bytenode is not supported atm.
