### ISSUE TITLE
Autoload does not allow mocking strategy like proxyquire

### ISSUE THREAD

**Issue by sf3ris** [fastify/fastify-autoload#220]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

3.22.0

### Plugin version

3.9.0

### Node.js version

14.18.1

### Operating system

Linux

### Operating system version (i.e. 20.04, 11.3, 10)

Ubuntu 20.04.3 LTS

### Description

This is not strictly a bug but more an unexpected behavior. 

It happened that the autoload plugin denies the possibility to use a mocking library like [proxyquire](https://github.com/thlorenz/proxyquire) for those modules imported via autoload.
For example if we autoload fastify routes, is not possible to mock routes imports.

### Steps to Reproduce

```js
// app.js
'use strict'

const path = require('path')
const AutoLoad = require('fastify-autoload')
const aRoutes = require('./routes/a.routes');

module.exports = async function (fastify, opts) {
  fastify.register(AutoLoad, {
    dir: path.join(__dirname, 'routes'),
    options: Object.assign({}, opts)
  })
  //fastify.register(aRoutes)
}


// routes/a.routes.js
const { a } = require('../a');

module.exports = async function (fastify, _, next) {
  fastify.get('/a', (request, reply) => {
    reply.send(a());
  });

  next();
};

// a.js
module.exports = {
  a: () => ({res: "A"})
};

// a.routes.test.js
const fastify = require('fastify');
const fp = require('fastify-plugin');
const proxy = require('proxyquire');

const app = fastify();

const application = proxy.noCallThru()('./app', {
  './a': {
    a: function(args) {
      return {res: "B"};
    },
    '@global': true
  }
}); 

app.register(application);

app.inject({url: '/a'})
  .then( res => {
    console.log(JSON.parse(res.payload)); // {res: "A"}
  });
```

Instead the above simple repro is working if we register the routes manually
```js
// app.js
'use strict'

const path = require('path')
const AutoLoad = require('fastify-autoload')
const aRoutes = require('./routes/a.routes');

module.exports = async function (fastify, opts) {
  /*fastify.register(AutoLoad, {
    dir: path.join(__dirname, 'routes'),
    options: Object.assign({}, opts)
  })*/
  fastify.register(aRoutes)
}


// routes/a.routes.js
const { a } = require('../a');

module.exports = async function (fastify, _, next) {
  fastify.get('/a', (request, reply) => {
    reply.send(a());
  });

  next();
};

// a.js
module.exports = {
  a: () => ({res: "A"})
};

// a.routes.test.js
const fastify = require('fastify');
const fp = require('fastify-plugin');
const proxy = require('proxyquire');

const app = fastify();

const application = proxy.noCallThru()('./app', {
  './a': {
    a: function(args) {
      return {res: "B"};
    },
    '@global': true
  }
}); 

app.register(application);

app.inject({url: '/a'})
  .then( res => {
    console.log(JSON.parse(res.payload)); // {res: "B"}
  });
```

### Expected Behavior

I would expect to be able to mock underlying modules even with the `fastify-autoload` plugin but I dont know if its possible at all.
Just wanted to write down a few lines, maybe it can help the next dev wondering why its not working.

If anyone has any suggestion if this is achievable in some way, I could try to work on this.

**Comment by sf3ris** [comment]
Quick link to a sandbox to reproduce the actual behavior
https://codesandbox.io/s/node-js-forked-o0rny?file=/app.js

**Comment by mcollina** [comment]
Unfortunately it's not supported and it likely won't be :(. It would complicate the codebase too much, and it's already too complicated.

**Comment by Eomm** [comment]
I must say that you can do it using the snippet I posted here:
https://github.com/fastify/fastify-cli/issues/453
and I did not find any existing mocking library that makes it works.

My opinion is that mock is needed sometimes - we can't pretend that every project is a beautiful place.
