### ISSUE TITLE
Typescript: No default export found in imported module for AutoLoad

### ISSUE THREAD

**Issue by TriStarGod** [fastify/fastify-autoload#221]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

3.27.0

### Plugin version

3.10.0

### Node.js version

v16.13.2

### Operating system

Windows

### Operating system version (i.e. 20.04, 11.3, 10)

10

### Description

I'm not sure when it occurred but for code `import AutoLoad, { AutoloadPluginOptions } from "fastify-autoload";`, vscode complains:

> No default export found in imported module "fastify-autoload" .eslint[[import/default](https://github.com/import-js/eslint-plugin-import/blob/v2.25.4/docs/rules/default.md)]

![image](https://user-images.githubusercontent.com/8272754/152438128-28379553-5491-4d99-a3e9-55391fcebd35.png)

However, the code runs just fine. At the moment, I'm ignoring with `// eslint-disable-next-line import/default`

### Steps to Reproduce

Import AutoLoad into a typescript fastify implementation.

### Expected Behavior

No error

**Comment by mcollina** [comment]
cc @fastify/typescript

**Comment by darkgl0w** [comment]
@TriStarGod > Can you please provide a GitHub repo with a minimal setup reproducing this issue so I can just clone it ?

**Comment by TriStarGod** [comment]
@darkgl0w  As requested

https://github.com/TriStarGod/fastify-autoload-ts-eslint-error/tree/master

**Comment by TriStarGod** [comment]
@darkgl0w I was pretty sure it linted correctly before. Anyway, thanks!
