### ISSUE TITLE
prefix trailing slash is not register for both /prefix & /prefix/ when using dirNameRoutePrefix

### ISSUE THREAD

**Issue by MomenNano** [fastify/fastify-autoload#223]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

3.27.1

### Plugin version

3.11.0

### Node.js version

16.131

### Operating system

Windows

### Operating system version (i.e. 20.04, 11.3, 10)

21H2

### Description

fastify autoload doesn't work as expected when using `dirNameRoutePrefix` option an setting it as a function to ignore some dir names, it will not register prefix trailing slash for both `/prefix` & `/prefix/`. it just registerr the last one with the slash in the end

### Steps to Reproduce

here I create a [reproducing repo](https://github.com/MomenNano/fastify-autoload-repro)

run the project and then do

`curl localhost:5000/user/` // this works
and
`curl localhost:5000/user` // this doesn't work :(

### Expected Behavior

both prefix trailing slash should be registered and works as the default fastify route `prefixTrailingSlash` option

**Comment by mcollina** [comment]
Thanks for reporting! Have you tried reproducing the same without fastify-autoload?

Have you seen https://www.fastify.io/docs/latest/Reference/Server/#ignoretrailingslash?

These settings are far from how I use Fastify and I'm unsure on all the possible combinations between them.

**Comment by MomenNano** [comment]
Hey, thanks for quick reply!
it works with `ignoretrailingslash` as a fastify option.

but I expect to see a consistent behavior when using autoload.

see that last commit on [reproduce repo](https://github.com/MomenNano/fastify-autoload-repro/commit/addbf2312a9272e5d0353cc525fe2544eeca0c41), and then try:
`localhost:5000/user/login/` // this work
`localhost:5000/user/login`  // this also work

**Comment by MomenNano** [comment]
> Have you tried reproducing the same without fastify-autoload?
Yes, I tried, and it seems like it the normal case in fastify. if you don't specify `ignoretrailingslash` as a option, it will search explicitly as what you specify in your route url.

but also -as I think- we should see a consistent behavior in autoload case.

**Comment by mcollina** [comment]
Would you like to send a Pull Request to address this issue? Remember to add unit tests.

**Comment by MomenNano** [comment]
Okay, I'll do it next week.
