### ISSUE TITLE
Tests are not completing with Jest + ESM

### ISSUE THREAD

**Issue by CyanoFresh** [fastify/fastify-autoload#225]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

3.27.4

### Plugin version

3.11.0

### Node.js version

16.14.0

### Operating system

Windows

### Operating system version (i.e. 20.04, 11.3, 10)

10

### Description

Hi.
As nodejs natively supports ESM since 16 version, I expect it to work properly. For now I cannot run tests using jest framework and fastify-autoload. Importing by hand and dynamic imports (`await import()`) work properly.

### Steps to Reproduce

Repository:
https://github.com/CyanoFresh/fastify-autoload-project

1. Run `npm test` (node flag is important)
2. Test with `fastify-autoload` fails to complete (process terminated). no error is displayed
3. Sometimes (like 1 in 10 runs) it displays error:
![image](https://user-images.githubusercontent.com/4249082/158064404-cb3e1c43-54ae-4535-b04d-49b69a05d238.png)

### Expected Behavior

Tests should run successfully.
I have tried different jest configurations but nothing helps. As I see in jest issues https://github.com/facebook/jest/issues/9430, required for auto-loading ESM functionality is supported

**Comment by mcollina** [comment]
Unfortunately jest support for esm is still experimental: https://jestjs.io/docs/ecmascript-modules. I would recommend you to not use native esm if you want to use jest.
