### ISSUE TITLE
autoload don't support the es6 module

### ISSUE THREAD

**Issue by kidyfirst** [fastify/fastify-autoload#25]
typescript module:
import fp from 'fastify-plugin'
import IFastifyInstance from '@airpay-sz/admin-common/dist/ts/types/IFastifyInstance'

export default fp(
(fastify: IFastifyInstance) => {
fastify.decorate('timestamp', function() {
return Date.now()
})
},
{
name: 'fastify-timestamp'
}
)
tsc to js code
"use strict";
var __importDefault = (this && this.__importDefault) || function (mod) {
return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
const fastify_plugin_1 = __importDefault(require("fastify-plugin"));
exports = fastify_plugin_1.default((fastify) => {
fastify.decorate('timestamp', function () {
return Date.now();
});
}, {
fastify: '>=2.x',
name: 'fastify-timestamp'
});
**the js code can't be load by fastify-plugin, because the plugin is an object**
Boot.prototype.use = function (plugin, opts) {
if (typeof plugin === 'function') { // the plugin is an object
this._addPlugin(plugin, opts, false)
} else {
throw new Error('plugin must be a function')
}

return this
}

so fastify-autoload module need to update
 if (plugin.autoload !== false) {
        // need to check the plugin whether or not the function
        fastify.register(plugin, pluginOptions)
 }

**Comment by mcollina** [comment]
This is not clear, can you please format your issue using code block? Also, it would be good to expand on what the problem actually is.

**Comment by kidyfirst** [comment]
i have submitted a  pull request, please check it.

**Comment by kidyfirst** [comment]
it have been supported now
