### ISSUE TITLE
Dependency from folder?!

### ISSUE THREAD

**Issue by yaneony** [fastify/fastify-autoload#261]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

latest

### Node.js version

16

### Operating system

Linux

### Operating system version (i.e. 20.04, 11.3, 10)

debian

### Description

Following, I have multiple plugins, like own session handler, database handlers and other, split into multiple directories. Those are loaded automatically with:

```
  app.register(autoload, {
    dir: path.join(path.dirname(url.fileURLToPath(import.meta.url)), 'core')
  });
  app.register(autoload, {
    dir: path.join(path.dirname(url.fileURLToPath(import.meta.url)), 'database')
  });
  app.register(autoload, {
    dir: path.join(path.dirname(url.fileURLToPath(import.meta.url)), 'libraries')
  });
```

It seems to work, just until I add some dependency to plugin in "core". For example, this plugin in "core":
```
import fp from 'fastify-plugin';

async function init(app, opts) {
  ...
}

export default fp(init, {
  name: 'core1',
  dependencies: ['database1']
});
```

And this plugin will be loaded from "database" folder:
```
import fp from 'fastify-plugin';

async function init(app, opts) {
  ...
}

export default fp(init, {
  name: 'database1',
  dependencies: []
});
```

If I put them together in one folder with only 1 autoload, everything is working fine. Is it possible to fix that or there is some workaround?!

### Steps to Reproduce

-

**Comment by mcollina** [comment]
There is no workaround, the dependencies would need to be in the same folder to work correctly. 
However, what you try cannot logically work because you are telling autoload to load all modules in `core`, `database`, and `libraries`. You might just want to invert the order of loads to:

```js
  app.register(autoload, {
    dir: path.join(path.dirname(url.fileURLToPath(import.meta.url)), 'libraries')
  });
  app.register(autoload, {
    dir: path.join(path.dirname(url.fileURLToPath(import.meta.url)), 'database')
  });
  app.register(autoload, {
    dir: path.join(path.dirname(url.fileURLToPath(import.meta.url)), 'core')
  });
```

**Comment by yaneony** [comment]
Yeah, I thought that it wouldn't work. Invert the order is not possible due to some cross dependencies. I will have to put them in one folder. But I found another workaround.

Create the following directory structure:
```
plugins
  core
  database
  libraries
```

After that, just load like this:
```
app.register(autoload, {
  dir: path.join(path.dirname(url.fileURLToPath(import.meta.url)), 'plugins')
});
```

Working like a magic :D
