### ISSUE TITLE
babel-node + typescript. Error only with autoloads :  throw new Error(@fastify/autoload cannot import plugin at '${file}'. To fix this error compile TypeScript to JavaScript or use 'ts-node' to run your app.)

### ISSUE THREAD

**Issue by Tumulte** [fastify/fastify-autoload#271]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

4.6.0

### Plugin version

5.4.0

### Node.js version

16.14.2

### Operating system

macOS

### Operating system version (i.e. 20.04, 11.3, 10)

12.6

### Description

I have a rather barebone `server.ts` (below) and I try to run it with typescript, ESM and hot reload.

I've set up a nodemon + babel command line : `  nodemon --exec 'babel-node -x .ts' app.ts` and everything works fine... except @fastify/autoload.

If I rename the autoload files as `.js` it works

I got this error : ` throw new Error(@fastify/autoload cannot import plugin at '${file}'. To fix this error compile TypeScript to JavaScript or use 'ts-node' to run your app.)`

I know there are several other issues with this error, but none have provided a solution. Thanks for your kind help, I can take alternative solutions for ESM+TS+hot reload if you know more compatible wayt

server.ts :
```javascript
import path from 'path'
import AutoLoad from '@fastify/autoload'
import {fastify} from "fastify";

let currentApp: string
const server = fastify()
server.register(require("@fastify/view"), {
    engine: {
        nunjucks: require("nunjucks"),
    },
    root: utils.configPath
});
server.addHook("preHandler", function (request, reply, done) {
    // @ts-ignore
    reply.locals = {
        picaro: path.resolve(__dirname, "index.njk")
    };
    done();
});

// This loads all plugins defined in plugins
// those should be support plugins that are reused
// through your application
server.register(AutoLoad, {
    dir: path.join(__dirname, 'plugins'),
})

// This loads all plugins defined in routes
// define your routes in one of these
server.register(AutoLoad, {
    dir: path.join(__dirname, 'routes'),
})

server.listen({port: 3000})
console.info('Loaded on port 3000')

```

### Steps to Reproduce

set up a basic fastify as typescript with babel-node (config below), launch the command `nodemon --exec 'babel-node -x .ts' app.ts`

```json
{
  "presets": [
    "@babel/preset-env",
    "@babel/preset-typescript"
  ],
  "plugins": [
    "@babel/plugin-proposal-class-properties"
  ]
}
```

### Expected Behavior

Autoloads should work with .ts autoload files

**Comment by mcollina** [comment]
I have no clue on how to help with this.

**Comment by mcollina** [comment]
Can you please create a full repo to reproduce? Or possibly send a PR?

**Comment by Tumulte** [comment]
@mcollina here you go https://stackblitz.com/edit/node-flfxgv?file=package.json,.babelrc,tsconfig.json,app.ts,routes%2Findex.ts

**Comment by lasmil** [comment]
I did some investigations on this and it looks like there was an attempt to support ts files:
https://github.com/fastify/fastify-autoload/pull/264
But it got reverted because of an issue in js files.

To use typescript files you need to use ts-node. In your example, use the following script:
`"scripts": {
    "start": "ts-node app.ts"
  },`

(you will need to install the missing dependencies).


To use javascript files, you can use babel-node like this:
`  "scripts": {
    "start": "babel-node -x \".js\" app.js"
  },`
(in your example, you will need to change the file extensions)

Besides these, what we can also do is try to use some bits of the PR mentioned above to be sure to load ts-node when needed. I will create a PR for that.
