### ISSUE TITLE
Add matchPattern to load only some specific paths

### ISSUE THREAD

**Issue by hugoattal** [fastify/fastify-autoload#287]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the feature has not already been requested

### 🚀 Feature Proposal

I'd like to match only some specific paths, ignoring every other files.

I suggest two things:

- Add a `matchPattern` that process the file only if it matches the pattern. If there is also an ignore pattern, I guess the order of priority should be `match, ignore` (if the route is matching, then check if it's ignored)
- Add the ability for `matchPattern` and `ignorePattern` to provide both Regex OR function that return a boolean OR string contained in the path.

ℹ️ I can do the PR if that's okay.

### Motivation

Here's my architecture:
```
/routes/user/handlers/get.ts (shoud load)
/routes/user/handlers/get.spec.ts (should ignore)
/routes/user/lib.ts (should ignore)
```

I could use the `ignorePattern` regex, but I feel like it's not a super intuitive DX.

### Example

Here's what my example could look like:

```ts
app.register(autoload, {
  dir: path.join(__dirname, "routes"),
  matchPattern: /handlers\/\w.ts$/
})

// or

app.register(autoload, {
  dir: path.join(__dirname, "routes"),
  matchPattern: /handlers/,
  ignorePattern: /spec\.ts$/
})

// or

app.register(autoload, {
  dir: path.join(__dirname, "routes"),
  matchPattern: "/handlers/",
  ignorePattern: (path) => path.endsWith("spec.ts")
})
```

**Comment by mcollina** [comment]
Go ahead with a PR!

**Comment by hugoattal** [comment]
Thanks! Done here: https://github.com/fastify/fastify-autoload/pull/289
