### ISSUE TITLE
dirNameRoutePrefix option doesn't work when set to false

### ISSUE THREAD

**Issue by hugoattal** [fastify/fastify-autoload#291]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

4.11.0

### Plugin version

5.7.0

### Node.js version

18.12.1

### Operating system

Windows

### Operating system version (i.e. 20.04, 11.3, 10)

Windows 11

### Description

I want to disable the `dirNameRoutePrefix` settings as my route already exposed their prefix
But routes aren't loading at all when setting `dirNameRoutePrefix: false`.

I think it comes from the fact that prefixes are used to index plugins in `hookedAccumulator`.
cf https://github.com/fastify/fastify-autoload/blob/master/index.js#L162
But I'm not 100% sure...

➡️ **If you want, I can investigate and make a PR to fix this!**

### Steps to Reproduce

Here's a small example

```ts
fastify.register(autoLoad, {
  dir: path.join(__dirname, 'plugins'),
  dirNameRoutePrefix : false
})
```

```ts
export default async (fastify: any) => {
  fastify.get("/foo/bar", function () {
    return { foo: "bar" };
  })
};
```

### Expected Behavior

Plugins/routes should load correctly.

**Comment by mcollina** [comment]
Thanks for reporting!

Can you provide steps to reproduce? We often need a [reproducible example](https://stackoverflow.com/help/minimal-reproducible-example), e.g. some code that allows someone else to recreate your problem by just copying and pasting it. If it involves more than a couple of different file, create a new repository on GitHub and add a link to that.

**Comment by hugoattal** [comment]
Ok, I'm really sorry, I should have dig into it a bit further... It appears that the `dirNameRoutePrefix` impacted the path sent to the `matchFilter` I had. So my `matchFilter` no longer worked.

For example, my filter function received this with the `dirNameRoutePrefix`: `/user/handlers/ping.ts`
And this without it: `///ping.ts`

100% my fault for not digging a bit. And another 100% my fault for building this very feature 😅...

I'll make a PR to fix this (else, the matchFilter and ignoreFilter don't have much use).
Again, so sorry...
