### ISSUE TITLE
autoloader breaks node --test --experimental-test-coverage

### ISSUE THREAD

**Issue by ahmadnassri** [fastify/fastify-autoload#329]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

4.23.0

### Plugin version

5.7.1

### Node.js version

20.6.1

### Operating system

Linux

### Operating system version (i.e. 20.04, 11.3, 10)

22.04

### Description

> **NOTE**  
> if this is best discussed / shared in node.js repos to help improve test coverage, then I'm happy to do that instead.

when using the node.js native test runner with the experimental code coverage, the test run freezes if `@fastify/autoload` is used.

```
node --test --experimental-test-coverage
```

I put together a sample repository here: https://github.com/ahmadnassri/temp-fastify-autoload

```
npm run test:plain # works
npm run test:coverage # freezes 
```

### Steps to Reproduce

```
git checkout https://github.com/ahmadnassri/temp-fastify-autoload ./demo
cd demo
npm install
npm run test:plain
```

### Expected Behavior

should see a thrown error / warning if there is an issue.

autoloading shouldn't hinder / break native code coverage functionality in node.js

**Comment by mcollina** [comment]
Unfortunately, the problem is in the code coverage of Node.js, not in autoload :/.

**Comment by ahmadnassri** [comment]
Roger that. I'll try in that org/repo
