### ISSUE TITLE
Cannot use with esm only

### ISSUE THREAD

**Issue by Joabesv** [fastify/fastify-autoload#332]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

4.23.2

### Plugin version

5.7.1

### Node.js version

20.6.1

### Operating system

macOS

### Operating system version (i.e. 20.04, 11.3, 10)

13.5.2

### Description

Hello there! 

Been having an error when importing routes with this plugin in an ESM enviroment.
For some reason it only happens with routes, when importing plugins the error does not happen. and only happens when using autoload

### Steps to Reproduce

just the repo if you prefer: https://github.com/Joabesv/esm-autoload

create a new fastify repo

mkdir esm-error-autoload

`pnpm add fastify @fastify/autoload @fastify/cors`

create a src/plugins and src/routes folder
create both server and app in the src root with this code

```js
// app.js
import { fastify } from 'fastify';
import { fastifyAutoload } from '@fastify/autoload';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const dirEsm = dirname(fileURLToPath(import.meta.url));
export const app = fastify({ logger: true });

try {
  await app.register(fastifyAutoload, {
    dir: join(dirEsm, 'plugins'),
    dirNameRoutePrefix: false,
    forceESM: true,
  });
  await app.register(fastifyAutoload, {
    dir: join(dirEsm, 'routes'),
    dirNameRoutePrefix: false,
  });
} catch (error) {
  app.log.error({ error }, 'fez merda');
  throw error;
}
```

```js
// server.js
import { app } from './app.js';

app.log.info(app.printRoutes());
await app.listen({ port: 5001 });
```

put a dumb plugin just to test (gets imported without any problemas)
```js
import { fastifyCors } from '@fastify/cors';

export default async (app, opts) => {
    app.register(fastifyCors);
    app.log.info('[PLUGIN] cors')  
}
```

place the route contents in routes/index.js

```js
export default async function (app) {
  app.get("/teste", () => ({msg: 'should work'}));
}
```

when autoload import the plugins folder nothing happens, but when it try to import the routes, i receive this error

```js
throw new AVV_ERR_PLUGIN_NOT_VALID(typeof plugin)
          ^
AvvioError [Error]: Plugin must be a function or a promise. Received: 'object'
```

### Expected Behavior

It should import both the plugins and the routes without any issues

**Comment by mcollina** [comment]
I agree the error should be better, but it's trying to load the `routes/handlers/test.js` file.
Configuring autoload only to load one level fixes it.

```diff
diff --git a/src/app.js b/src/app.js
index e6cb15e..38f0b5c 100644
--- a/src/app.js
+++ b/src/app.js
@@ -15,6 +15,7 @@ try {
   await app.register(fastifyAutoload, {
     dir: join(dirEsm, 'routes'),
     dirNameRoutePrefix: false,
+    maxDepth: 0,
   });
 } catch (error) {
   app.log.error({ error }, 'fez merda');
```
