### ISSUE TITLE
ts-node error with plugins using custom instance field via declaration merging

### ISSUE THREAD

**Issue by nicolas-goudry** [fastify/fastify-autoload#339]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

4.24.3

### Plugin version

5.8.0

### Node.js version

18.18.2

### Operating system

Linux

### Operating system version (i.e. 20.04, 11.3, 10)

Arch

### Description

Using a custom instance field declared via declaration merging in plugin A from plugin B fails.

The real code is in the reproducing repository, but basically we have plugin A that declares a custom field on the `FastifyInstance` interface, then plugin B needs to use this field and does so. TypeScript is happy, build works, built app works, but `ts-node` fails to run the code and complains about the custom field not existing on `FastifyInstance`.

### Steps to Reproduce

Clone the [repository](https://github.com/nicolas-goudry/fastify-autoload-ts-node-issue-declaration-merging), install dependencies, then:

- try to build the app: `npm run build` => works
- try to run the built app: `NODE_ENV=development node dist/index.js` => works
- try to run the TS files through `ts-node`: `npm start` => fails

### Expected Behavior

Since the code builds successfully and works, I would expect to be able to run it with `ts-node` the same way.

**Comment by mcollina** [comment]
Thanks for reporting. Unfortunately there is not much you can do. The only solution is to add a a TS reference field to load the file that defines the new decorator.
