### ISSUE TITLE
Achieve 100% test coverage

### ISSUE THREAD

**Issue by jean-michelet** [fastify/fastify-autoload#369]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the issue has not already been raised

### Issue

I'd like to try to increase test coverage, are you interested?

**Comment by Uzlopak** [comment]
sure, PRs are welcome ;)

**Comment by jean-michelet** [comment]
Let me know if there are other components that could benefit from increased code coverage.
It's not always feasible but I can try, it helps me learn the internals.

Maybe these ones?
- https://github.com/fastify/fastify-reply-from/blob/master/.taprc
- https://github.com/fastify/under-pressure/blob/master/.taprc

**Comment by gurgunday** [comment]
Those would be great, yeah
