### ISSUE TITLE
autohooks break prefixOverride

### ISSUE THREAD

**Issue by rommelandrea** [fastify/fastify-autoload#380]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

4.27.0

### Plugin version

5.8.1+

### Node.js version

20.12.2

### Operating system

Linux

### Operating system version (i.e. 20.04, 11.3, 10)

Linux

### Description

From autoload 5.8.1 onward, if an autohook is defined and there is an override of the prefix defined in either hooks or route, the override will be ignored.

### Link to code that reproduces the bug

https://github.com/rommelandrea/fastify-autoload-bug

### Expected Behavior

when prefixOverride is exported the route change the prefix instead of use the default.

**Comment by mcollina** [comment]
cc @climba03003 wdyt?

**Comment by climba03003** [comment]
It is a complicated problem, I think we should
1. Revert all changes related to #368
2. Rework the files finding and tree building - it is the critical one because all the information is scattered currently.
3. Re-land the feature in 1.

**Comment by mcollina** [comment]
@jean-michelet wdyt?

**Comment by jean-michelet** [comment]
I am gonna investigate, but climba probably knows the component better than I do so if I struggle to fix this issue I will push a revert PR as suggested.

**Comment by mcollina** [comment]
Thanks @jean-michelet

**Comment by jean-michelet** [comment]
I will do it tomorrow or Friday at the latest, sent you a DM on Discord @mcollina

**Comment by jean-michelet** [comment]
https://github.com/rommelandrea/fastify-autoload-bug/blob/a2720e87a4c5d6fbfc6029868989774e525d1da8/routes/example/autohooks.js#L7
Autohooks plugins are managed as an independent tree without all these helpers @rommelandrea 
Maybe we can add a note to the doc.

To reverse #368, I also need to reverse #374, if I understand correctly. Can you confirm before I push @climba03003?

At the moment, it's difficult to solve this issue... We should state in the documentation that `setNotFoundHandler` cannot be used in autohooks. If people really need this feature, they'll push a PR with tests. But I think I will take the time to refactor the whole component as suggested.

**Comment by jean-michelet** [comment]
This test breaks when I revert:
https://github.com/fastify/fastify-autoload/blob/24e352a30980402ae680b8f9a3ca88a3b73459af/test/issues/374/test.js#L37

**Comment by climba03003** [comment]
@jean-michelet 
You should revert #378, #375 and #368 in order
