### ISSUE TITLE
Route auto-prefixing docs still relevant?

### ISSUE THREAD

**Issue by tobiasmuehl** [fastify/fastify-autoload#45]
According to the docs routes in folders will be prefixed with the folder name automatically. I can't confirm this behavior with fastify 2.7.1 and fastify-autoload 1.0.0

**Comment by mcollina** [comment]
Ouch, this seems off. Would you mind sending a PR with the fix for your case? The code that implements that is still in tree.

**Comment by tobiasmuehl** [comment]
Haven't fixed this, instead just resorted to not using autoload. Not sure what the fix is. If no one else can reproduce this problem we can close the issue

**Comment by Eomm** [comment]
Maybe it is a bit confusing because only the subfolders are used as a prefix in the route definition.

From this example:

```
const f = require('fastify')
const path = require('path')
const fastify = f({ logger: true })
fastify.addHook('onRoute', (r) => console.log(`${r.path}`))
fastify.register(require('./index'), {
  dir: path.join(__dirname, 'folder')
})
fastify.listen(3000)
```

`folder` will never be shown as route path.

But if you put your routes in a subfolder:

![image](https://user-images.githubusercontent.com/11404065/62809496-6674d080-bafb-11e9-837b-73566717e918.png)

You will get the prefix.

**Comment by tobiasmuehl** [comment]
Can't reproduce what you're saying. Made a demo here: https://codesandbox.io/embed/fastify-autoload-0s5ib

You'd expect `/subfolder/test` to render something but it 404s. `/test` works.

**Comment by Eomm** [comment]
Could you give it a try locally and npm?
I can't reproduce the error and in sandbox, all seems good, but as you pointed out dosen't work

**Comment by tobiasmuehl** [comment]
Ah, should put that in the documentation. Can open a PR in the next few days, or do you @hazam want to give it a shot?
