### ISSUE TITLE
Automatically wrap route files

### ISSUE THREAD

**Issue by PatrickHeneise** [fastify/fastify-autoload#54]
## 🚀 Feature Proposal

We're migrating an API to fastify and somehow the boilerplate

```
module.exports = function (fastify, opts, next) {
  fastify.route({
    method: 'GET',
    url: '/',
    handler
  })
}
```

feels a bit clunky. I'd like to propose just the route content in a file:

```
module.exports = {
  method: 'GET',
  url: '/',
  handler
}
```

For most cases this is totally sufficient. If additional config/options are required, a regular plugin/route function can be exported.

## Motivation

As mentioned above, the plugin structure feels a bit clunky in each and every file.

## Example

The default type is a function and the new proposal would be an object (method is always required anyway), so I'm thinking somewhere along the lines of (https://github.com/fastify/fastify-autoload/blob/master/index.js#L110):

```
const content = require(file)
let plugin

if (content && typeof content === 'object' && content.method) {
  plugin = function (fastify, opts, next) {
    fastify.route(content)
    next()
  }
} else {
  plugin = content
}
```

This is non-breaking, but to be safe it could also be flagged with an new option "wrapRoutes" or something like that.

I'm testing this locally, but I'm currently getting an error when running `npm test`?

```
test/error.js ......................................... 1/2
  not ok should match pattern provided
    found: >-
      Unexpected token '}' at
      /Users/patrick/Sites/fastify-autoload/test/error/lib/a.js:6
    pattern: '/Unexpected token \} at .*\/test\/error\/lib\/a.js:6/'
    at:
      line: 14
      column: 5
      file: test/error.js
    stack: |
      test/error.js:14:5
      Object._encapsulateThreeParam (node_modules/avvio/boot.js:408:13)
      Boot.callWithCbOrNextTick (node_modules/avvio/boot.js:339:5)
      release (node_modules/fastq/queue.js:127:16)
      Object.resume (node_modules/fastq/queue.js:61:7)
      node_modules/avvio/boot.js:155:20
      node_modules/avvio/plugin.js:178:7
      done (node_modules/avvio/plugin.js:136:5)
      check (node_modules/avvio/plugin.js:147:7)
    source: |
      t.match(err.message, /Unexpected token \} at .*\/test\/error\/lib\/a.js:6/)
```

**Comment by jsumners** [comment]
You can already do what you desire:

```js
const routes = fs.readdirSync('path/to/routes/dir/')
routes.forEach(r => fastify.route(r))
```

The plugin pattern you show in your first example is merely the recommended method. It provided encapsulation and makes it easier to test individual routes.

**Comment by PatrickHeneise** [comment]
Oh that's neat! Will try.

**Comment by jsumners** [comment]
I thought this issue was on the core repo. I didn't realize it is in the autoload plugin repo. I know nothing of how this plugin works.

**Comment by PatrickHeneise** [comment]
Thanks anyway! Right now we don‘t have any special cases, so this might do the trick, but in the long run I think it‘s better to solve this in the autoloader.

**Comment by mcollina** [comment]
It would be great if you'd like to send a PR.

**Comment by PatrickHeneise** [comment]
I will. As mentioned, I can't get the tests to pass on `master` at the moment and wonder what's going on there?

**Comment by mcollina** [comment]
Can you open a seperate issue with the error you are getting?

**Comment by PatrickHeneise** [comment]
Done. See #55
