### ISSUE TITLE
Import all plugins in parallel

### ISSUE THREAD

**Issue by mcollina** [fastify/fastify-autoload#78]
In https://github.com/fastify/fastify-autoload/blob/41983a1ca5f06c7c73affc718e82eeaeacf62b80/index.js#L21-L30, the plugins are loaded one at a time.

Given `import()` is async, it's possible to parallelize it so they would load faster.

**Comment by iainjreid** [comment]
Submitted a PR to apply this change! 👍

**Comment by mcollina** [comment]
Good work!
