### ISSUE TITLE
How to apply a lifecycle hook to all plugins in a folder

### ISSUE THREAD

**Issue by mcollina** [fastify/fastify-autoload#79]
It would be really handy to be able to set a few lifecycle hooks for each folder. This would be really handy to add authentication for a specific folder folder for example.

**Comment by iainjreid** [comment]
Hi @mcollina, would this be a good first issue? If so, is this the sort of interface you were thinking of?

```javascript
app.register(autoload, {
  dir: path.join(__dirname, 'plugins')
  hooks: {
    onRequest: [auth]
  }
})
```

**Comment by mcollina** [comment]
I was thinking more of a .autoload.js file that is automatically loaded with fastify-plugin for a given folder.

**Comment by iainjreid** [comment]
Something like this?

```javascript
// .autoload.js
module.exports = {
  onRequest: [auth]
}
```

Should developers be able to have a different `.autoload.js` files in each plugin directory where needed (replacing the hooks inherited from the parent directory)?

**Comment by mcollina** [comment]
I would go and make .autoload.js a full plugin. Yes, those should be nested.

**Comment by iainjreid** [comment]
I'm really sorry, but I've looked through the codebase and I'm not sure how to go about this, could you point me in the right direction?

I can see how adding an extra block of code to the `fastifyAutoload` function could load an `.autoload.js` file and use the contents to mutate each plugin found in the child directories upon registration.

**Comment by mcollina** [comment]
Roughly given this tree:

```
/routes/a/
  |- .autoload.js
  |- b.js
```


Note that in order to achieve encapsulation you would need to always create a new plugin in https://github.com/fastify/fastify-autoload/blob/master/index.js#L79, and then call then call https://github.com/fastify/fastify-autoload/blob/dd3f3312bd8fbf01cbf7b4375932a5fbf2aeb55f/index.js#L157 on this plugin. You would need to reset the `prefix` when doing this.

After doing this, you just register `autoload.js` on this intermedia plugin.

**Comment by kswope** [comment]
Just starting looking at a minimalist JS framework for a larger project and fastify looks like its almost a perfect fit but this particular issue is a bit of a show stopper for me and may force me up to less minimal framework.

The autoload plugin is really a killer feature for a minimal framework (Its strange I had to find it in the starter template, its never mentioned in the docs at all!)

But the problem, brought up in this issue, is that there’s no easy way to scope a plugin to a “branch” of the routes.

I came up with a ‘handoff’ strategy but it really seems like the plugin is almost there.

Here’s an example I’m experimenting with.  You can see I’d like to both version the API and have a public and private branch (obviously the private branch will have an auth prehandler in all the end points)

```
│   └── routes
│       ├── root.ts
│       └── v1
│           ├── autoload.ts
│           ├── private
│           │   └── data
│           │       └── index.ts
│           └── public
│               └── data
│                   └── index.ts

``` 

Here’s the trick, there’s multiple autoload calls.

In the app.ts (not shown) there’s (note the maxDepth)

```
  void fastify.register(AutoLoad, {
    dir: path.join(__dirname, "routes"),
    maxDepth: 1,
    options: opts,
  })

```

Inside the V1 version directory is a file named autoload.ts (or your own preference).

```
const autoloader: FastifyPluginAsync = async (fastify, opts): Promise<void> => {

  // private register
  fastify.register(async (fastify) => {
    fastify.addHook("preHandler", async (_request, _reply) => {
      console.log("!!! in auth prehandler");
      // return await v1Auth();
    });
    fastify.register(AutoLoad, {
      dir: path.join(__dirname, "private"),
      options: { ...opts, prefix: "private" },
    });
  });

  // public register
  fastify.register(AutoLoad, {
    dir: path.join(__dirname, "public"),
    options: { ...opts, prefix: "public" },
  }):
};

```

If this works, and it seems to, then not only can I just add new API versions, password protect a tree branch, but even change the authentication method in different versions.

What I don’t like, its so kludgy.  You have to keep track of things like prefix or you end up with paths like '/v1/v1/public/data' and mess with nested registers (I think thats the only way that works)

I like the concept of a dot-autoload file, but there’s no way I’m guarding users private data with a dot-file!  It will be one of the most important files that exist, why make that a dot file?

Maybe add an option to autoload used like (applied hooks to current directory and subs)

```
  fastify.register(AutoLoad, {
    dir: path.join(__dirname, "public"),
    hookFile: “hooks.ts”
    options: opts,
  });
```

**Comment by Eomm** [comment]
> You can see I’d like to both version the API and have a public and private branch

I use the same approach since with this structure there is no doubt about what should be public and what should not.
I was using a custom private plugin to do so, but with #124 you can now write:

```
  fastify.register(autoLoad, {
    dir: path.join(__dirname, 'routes'),
    dirNameRoutePrefix: function rewrite (folderParent, folderName) {
      if (folderName === 'public' || folderName === 'private') {
        return false
      }
      return folderName
    }
  })
```

So you may centralize all the prefix logic/configuration in the plugin registration and not across the directories (I prefer so since it seems clearer to me to find routes through projects)

**Comment by mcollina** [comment]
> Just starting looking at a minimalist JS framework for a larger project and fastify looks like its almost a perfect fit but this particular issue is a bit of a show stopper for me and may force me up to less minimal framework.

The fastify community is a place where we maintain the framework together. If you'd like to add some features to this module, improve its docs, or anything else... please send a PR (with tests).

**Comment by kswope** [comment]
>  The fastify community is a place where we maintain the framework together. If you'd like to add some features to this module, improve its docs, or anything else... please send a PR (with tests).

Aren't you the one who started this issue?  I've been evaluating fastify for a total of 3 days now and thought I'd offer some feedback about a feature you seem to be discussing here and why its important to me.

**Comment by mcollina** [comment]
I meant that if:

> this particular issue is a bit of a show stopper for me and may force me up to less minimal framework.

Then it's up to you to implement it. This issue has been going on for some time and I agree with you it's something this library should do. Threatening to use some other library alienates the maintainers very quickly.

**Comment by kswope** [comment]
> Threatening to use some other library alienates the maintainers very quickly.

I didn't mean it as a threat.  I'm not sure how anybody could think that especially since I included my current use case, my current solution and my feedback on the proposed solution.  The next poster even agreed with my current approach.

> Then it's up to you to implement it.

So PR or shut up?  There's no discussion or feedback in this community?  Especially on an issue that was opened and stalled half a year ago?  That's very discouraging to a new user.

**Comment by mcollina** [comment]
> I didn't mean it as a threat.

I'm sorry I misunderstood - we had quite a few of those lately. I probably suffer from some OSS fatigue where a lot of people ask for features, but they are not willing to spend the time implementing or maintaining them.

**Comment by bluebrown** [comment]
> > You can see I’d like to both version the API and have a public and private branch
> 
> I use the same approach since with this structure there is no doubt about what should be public and what should not.
> I was using a custom private plugin to do so, but with #124 you can now write:
> 
> ```
>   fastify.register(autoLoad, {
>     dir: path.join(__dirname, 'routes'),
>     dirNameRoutePrefix: function rewrite (folderParent, folderName) {
>       if (folderName === 'public' || folderName === 'private') {
>         return false
>       }
>       return folderName
>     }
>   })
> ```
> 
> So you may centralize all the prefix logic/configuration in the plugin registration and not across the directories (I prefer so since it seems clearer to me to find routes through projects)

Is this not already the missing piece?

Could we not check for dotfile or such in this callback?  If condition is met, register a new plugin and call autoload again inside the new scope?

**Comment by polymathca** [comment]
I forked and took a shot at this, I'm not sure if the code-style is in line with the rest of the project, but if it's looking good and fulfills this request, I will write some tests, docs, and make a PR. I have done some basic testing on my system, but didn't want to get too far into the weeds without another set of eyes on it! Here are the main points:

Works with dots or underscore prefixes (or unprefixed)
```js
autoHooksPattern: /^[_\.]?auto_?hooks(\.ts|\.js|\.cjs|\.mjs)$/i,
```

Uses fastify-plugin to encapsulate route and expose hooks
```js
  if (hooks && hooks.length > 0) {

    // plugin has hooks, which we need to encapsulate at the same layer as the plugin      
    fastify.register(async function(app, opts) {      
      for (let hook of hooks) {        
        app.register(fp(hook), options);
      };
      
      app.register(plugin, options);
    })
  } else {

    // register plugin as normal
    fastify.register(plugin, options);
  }
```

Adds a few hook-related options to the config:
```js
    app.register(autoload, {
        dir: join(import.meta.url, 'routes'),
        autoHooks: true, // false: ignore autohook files so they don't pollute anything
        cascadeHooks: false, // true: hooks will be applied to all child routes, false: will only apply to current folder
        overwriteHooks: true // true: a new autohook file will start a new cascade, false: a new autohook file will add to the chain
    })
```

Full file can be found here: https://github.com/polymathca/fastify-autoload/blob/autoload-hooks/index.js

Hopefully this is some help!

**Comment by mcollina** [comment]
would you like to send a PR @polymathca?

**Comment by polymathca** [comment]
For sure! Do you want me to wait until I write some tests and clean up the code, or should I submit it now?

**Comment by AyoubElk** [comment]
@polymathca you could open a draft PR and we'll provide guidance if neede regarding tests.
Thanks!

**Comment by polymathca** [comment]
Sounds good! This is my first contribution, so I'm sure there are some rough edges.

**Comment by kswope** [comment]
What is with the dot files?  Has everybody forgotten that dot files exist to optionally hide files from shell apps?  How is that a good idea for authentication code?  They don't mean "special" files.  Why not just let the user specify their own hook file name?

**Comment by polymathca** [comment]
> 
> ```js
> autoHooksPattern: /^[_\.]?auto_?hooks(\.ts|\.js|\.cjs|\.mjs)$/i,
> ```
>

This can be changed in the `autoload` options object.

Dot files were mentioned earlier in the thread, and felt like a logical default given existing conventions and expectations (e.g. `.htaccess`, `.env`, `.gitignore`, etc...), as well as the idea that any 'magic' files such as these should stand out in their directory.

**Comment by kswope** [comment]
> Dot files were mentioned earlier in the thread, and felt like a logical default given existing conventions and expectations (e.g. `.htaccess`, `.env`, `.gitignore`, etc...), as well as the idea that any 'magic' files such as these should stand out in their directory.

Those files explicitly aren't part of your app, the file you propose is.

**Comment by polymathca** [comment]
Absolutely. It's a useful starting point for someone who is just starting out with the software, and the flexibility is there to allow for more advanced users to configure it as they deem necessary to meet with their conventions.

**Comment by kswope** [comment]
> Absolutely. It's a useful starting point for someone who is just starting out with the software, and the flexibility is there to allow for more advanced users to configure it as they deem necessary to meet with their conventions.

Then you should put a disclaimer in whatever app you use this library in that dot-files related to security may be present in some directories and make sure your editor is configured to show dot files.

**Comment by franciscolourenco** [comment]
Does it make sense to use the `autohooks.js` file define decorators or is this intended just for hooks?

**Comment by polymathca** [comment]
> 
> 
> Does it make sense to use the `autohooks.js` file define decorators or is this intended just for hooks?

I've been using it for hooks and decorators, it's very handy to be able to alter behaviour for specific routes and their children (e.g. add multi-part support to only a segment of my API instead of enabling it application-wide).
