### ISSUE TITLE
pluginMetadata is empty in v1.2.2

### ISSUE THREAD

**Issue by JacopoDaeli** [fastify/fastify-autoload#82]
https://github.com/fastify/fastify-autoload/blob/67d78db66c4ab7b6d593e9dbbecc2b22d49975ed/index.js#L124

Hello, dependencies loading are not respected because it seems that `plugin[Symbol.for('plugin-meta')]` is always `undefined`.

To create my plugins I'm using `fastify-plugin@1.6.1`.

For instance when I print `plugin` in some of my code I get:
```js
{
  default: [Function: connectDynamoDB] {
    [Symbol(skip-override)]: true,
    [Symbol(fastify.display-name)]: 'dynamodb-connector',
    [Symbol(plugin-meta)]: {
      name: 'dynamodb-connector',
      fastify: '2.x',
      decorators: [Object],
      dependencies: [Array]
    }
  }
}
```

Therefore I believe we should change to `const pluginMeta = plugin.default[Symbol.for('plugin-meta')] || {}`.

Does it make sense to fix this and publish a `v1.2.3`?
Although, I'm not sure it is still possible (cc. @mcollina).

**Comment by mcollina** [comment]
Are you transpiling with babel or typescript (or any other lib)?
Please send a PR! Can you also check if this happens with master? It has a different codebase, so we cannot backport easily.

**Comment by JacopoDaeli** [comment]
@mcollina the issue is not in `master`. It looks like `v3.x` has not the problem.
However folks using `fastify@2.x` which need to use `fastify-autoload@1.x` (otherwise we would get some `Typescript` errors. We could create a separate branch for autoload `1.x`, starting from [this commit](https://github.com/fastify/fastify-autoload/commit/67d78db66c4ab7b6d593e9dbbecc2b22d49975ed), and push there the fix?

**Comment by JacopoDaeli** [comment]
Oh forgot to mention. The issue happens both when transpiring using `tsc`, but also when using `node-ts` directly.

**Comment by mcollina** [comment]
I think it's due to some of the options you have configure ts with.

Feel free to send a PR, I've created the branch: https://github.com/fastify/fastify-autoload/tree/v1.x
