### ISSUE TITLE
make folder-name based prefixes optional

### ISSUE THREAD

**Issue by davidmarkclements** [fastify/fastify-autoload#84]
## 🚀 Feature Proposal

Allow an option `dirNameRoutePrefixing`

Default to `true` as per current behaviour. When set to `false` any index.js files in folders registering routes will not auto prefix routes registration with directory name. 

## Motivation

The reason is migration from fastify v2. People will not be expecting routes registered in subfolders to change. 

## Example

```js
  fastify.register(AutoLoad, {
    dir: path.join(__dirname, 'routes'),
    dirNameRoutePrefixing: false,
    options: Object.assign({}, opts)
  })
```

**Comment by jsumners** [comment]
How does this relate to v2? This is a separate optional module.

**Comment by Eomm** [comment]
I would propose that this parameter would be a sync function that:

- if return a falsy value a prefix is not added
- if return a string, it will be used as prefix

```
  fastify.register(AutoLoad, {
    dir: path.join(__dirname, 'routes'),
    prefixBuilder: function (dirName, dirPath) {
         if(dirName === 'private') return false
         if(dirName === 'legacy') return 'i-wanna-cy'
         return `prefix-${dirName}`
    },
    options: Object.assign({}, opts)
  })
```

I use this in my daily job (with a custom autoload plugin).
I have a project structure like this:
- private/
  - plugins.js
  - legacy/
      - routes.js
  - user/
      - routes.js
- public/
  - user/
      - routes.js

Where the plugins in private are loaded only for sub-context and in public there is not any db connection etc..
In this usage, I don't want the `/private` or `/legacy` folder will be used as prefix in my routes endpoint
