### ISSUE TITLE
Jest -> ts-jest + Typescript does not appear to be working

### ISSUE THREAD

**Issue by wolfejw86** [fastify/fastify-autoload#86]
## 🐛 Bug Report

In Fastify-Autoload 1.x jest tests + typescript worked with fastify-autoload with seemingly no issue as long as the `includeTypescript: true` configuration was passed.  With the new version it appears that has been removed in favor of automatically supporting ts-node.  I don't 100% know everything about ts-jest but I do not believe it uses ts-node and yet it worked before.  It seems like this should still work.

## To Reproduce

clone this repo - https://github.com/wolfejw86/fastify-typescript-starter

run `npm install`
run `npm run test`

see that fasitify-autoload is working correctly in https://github.com/wolfejw86/fastify-typescript-starter/blob/master/src/app.ts

In the same repo - upgrade fastify-swagger, fastify, fastify-plugin, and fastify-autoload all to the latest version by switching to the branch in progress(the 3.0 migration for fastify + typescript).
`git checkout fastify-upgrade`
`npm install`
`npm run test`

Notice fastify-autoload will no longer load any plugins.

```
fastify-autoload cannot import plugin at '/Users/johnwolfe/Desktop/repositories/fastify-typescript-starter/src/plugins/globalErrorHandler.ts'. To fix this error compile TypeScript to JavaScript or use 'ts-node' to run your app.

      at findPlugins (node_modules/fastify-autoload/index.js:87:15)
      at fastifyAutoload (node_modules/fastify-autoload/index.js:19:19)
```

Edit:
Additionally if I hardcode this line:
![image](https://user-images.githubusercontent.com/22133869/87222904-00657e80-c346-11ea-905c-8b70d1c7fb4d.png)

~It _mostly_ works, but doesn't load an `index.ts` file in the services folder from:~ EDIT: it works fine - I did not correctly understand the new behavior of how autoload plugin handles nested folders
~I am waiting for `fastify.ready()` but it seems like it's firing before the second call to the autoload plugin has finished resolving or something.~ EDIT: It loads all modules correctly according to how Autoload uses nested folders as pathnames now.

Any help is appreciated :)

**Comment by mcollina** [comment]
I think you have two problems:

1. ts-node detection seems not working when using ts-jest.
2. how do you know the index.ts file is not being loaded?

**Comment by wolfejw86** [comment]
Yeah that’s probably fair.
1. I think the assertion check for whether or not you’re in a typescript env is just too strict. If I set it to true it at least loads the top level files.

2. For how I know, if you take a look at my tests, they assert that a route from example/index.ts is called via fastify.inject.  In the 1.x version of Autoload it works just fine, in the latest version that route gets a 404 in that test which tells me it’s not there (aka I don’t think it’s getting loaded)

**Comment by mcollina** [comment]
As for 2, it's loaded. The `/example` prefix is automatically added based on the folder name. This is one of the changes in the newer major of fastify-autoload.

The problem is only that the check is too strict for some reason.

**Comment by wolfejw86** [comment]
Oh interesting, I missed that in the docs and now I see that if I change it, it works.  @mcollina sorry about the confusion on my part there, thanks for explaining it. So changing those routes to not already include the folder name in the path worked 👍 .

So yes, I guess it just comes down to line 8 of `index.js` in `fastify-autoload`;

`const typescriptSupport = Symbol.for('ts-node.register.instance') in process`;

For now I'm hacking around it by doing this in my jest config + a javascript file I load before each test:
```
/// jest.config
module.exports = {
  restoreMocks: true,
  clearMocks: true,
  collectCoverageFrom: ['src/**/*.{ts,js}'],
  coverageDirectory: 'coverage',
  setupFiles: ['./forceTsNodeSymbolOnProcess.js'],
  moduleFileExtensions: ['ts', 'js', 'json'],
  testEnvironment: 'node',
  testMatch: ['**/?(*.)(spec|test).ts?(x)'],
  testPathIgnorePatterns: ['/node_modules/', '/coverage/', '/dist/'],
  preset: 'ts-jest',
};
```
and my hacky solution 🤣 :
```
// forceTsNodeSymbolOnProcess.js
process[Symbol.for('ts-node.register.instance')] = true;
```

Just curious, why not just let the plugin consume typescript files and assume that if someone is doing so, they are running the app in a manner that supports that?

**Comment by mcollina** [comment]
I think the idea is to provide a meaningful error to the user. Maybe we can get a similar symbol for ts-jest.

**Comment by wolfejw86** [comment]
Ah yeah that makes sense. I will take a look around and see

**Comment by wolfejw86** [comment]
Response from person in `ts-jest` slack community - 
![image](https://user-images.githubusercontent.com/22133869/87330201-34879d80-c506-11ea-9713-e499fe53d25d.png)

**Comment by mcollina** [comment]
I guess we were too optimistic in our ability to support this automatically. We should add back the `includeTypescript` flag as an ovverride for the auto-detect logic we currently have. Can you send a PR?

**Comment by wolfejw86** [comment]
yes i'll be happy to. i have kind of a crazy week but will knock it out over the weekend if that's okay :)

**Comment by mcollina** [comment]
go for it!

**Comment by gjritter** [comment]
FYI, the fix in https://github.com/fastify/fastify-autoload/pull/95 works when running jest via something like `npm run test`, but does not when running `npx jest`, as `npm_package_devDependencies_ts_jest` is not in process.env when running `npx jest`.

**Comment by mcollina** [comment]
There should be no real difference between the two.
