### ISSUE TITLE
Only load top-level directories

### ISSUE THREAD

**Issue by MichielDeMey** [fastify/fastify-autoload#89]
## 🚀 Feature Proposal

Before the support for subdirectory loading, we only loaded top-level directory `index.js` files,
since v3 we have the ability to load automatically from subdirectories.

I saw a PR that would add a `recursive` option to configure loading subdirectories or not (https://github.com/fastify/fastify-autoload/pull/72).
Loading of subdirectories was actually fixed in https://github.com/fastify/fastify-autoload/pull/76, but I could not find a similar option implemented.

## Motivation

The motivation is for upgrading the autoloader with an existing file structure that was not built for loading plugins recursively.
All our modules are defined at the top-level and we have other (non-fastify) code in there.

## Example

Example directory structure:
```
modules
├── auth
│   ├── controller.js
│   ├── handlers.js
│   ├── index.js
│   └── schemas
│       ├── index.js
│       ├── login
│       └── register
└── root.js
```
This issue here is that it will try to load `schemas/index.js` as a Fastify plugin.

I believe the initial proposal of having a `recursive` option when setting up the autoloader was a good idea.
```js
fastify.register(AutoLoad, {
  dir: path.join(__dirname, 'modules'),
  recursive: false
})
```

Right now we're solving this by having a really big `ignorePattern` RegEx but that won't scale very well. 🙂

**Comment by mcollina** [comment]
Would you like to send a Pull Request to address this issue? Remember to add unit tests.

**Comment by MichielDeMey** [comment]
PR #108 fixes this issue. Thanks @HW13 ! 👍
