### ISSUE TITLE
Wired url when register from root dir

### ISSUE THREAD

**Issue by MomenNano** [fastify/fastify-autoload#91]
## 🐛 Bug Report
when using fastify-autoload with router in the root directory with no path `fastify.get('/')` and prefix option

## To Reproduce

app.js
```js
server.register(autoload, {
	dir: path.join(__dirname, 'dir'),
	options: { prefix: 'v1/' }
})
```

dir/index.js
```js
module.exports = async (server, opts) => {
	server.get('/', async (req, reply) => {
		reply.send({ works: true })
	})
}
```
## Expected behavior

register only
`/v1
/v1/`

## Actual  behavior
it register
`/v1/
/v1//`
![image](https://user-images.githubusercontent.com/22351955/87495316-635e5a80-c651-11ea-86bd-69ca02952662.png)

## Your Environment

- *node version*:12
- *fastify version*: >=tested on both 3.0.0 and 2.15
- *os*:  Windows

**Comment by mcollina** [comment]
What options are you passing to fastify? Have you tried _without_ autoload?

**Comment by MomenNano** [comment]
I'm not passing any option to fastify, and when I tried without autoload (with register only) it caused the same wired behavior.
so maybe it's a fastify bug
![image](https://user-images.githubusercontent.com/22351955/87567153-3eef9600-c6c4-11ea-855e-65fbe0c38eab.png)

**Comment by mcollina** [comment]
It looks like it. Would you mind to open an issue there? In the meanwhile, use `/v1` as a prefix, as it will work as intended.
